version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-flask-webapp
    ports:
      - "5000:5000"
    environment:
      http_proxy:
      https_proxy:
      no_proxy: